remote_theme: chrisrhymes/bulma-clean-theme
title: Parallel Sparse Computation Toolkit
email: eocoe@na.iac.cnr.it
description: Scientific Computing towards the Exascale
permalink: pretty
url: "psctoolkit.github.io"
favicon: /favicon.png # Favicon is in the standard position

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
