remote_theme: chrisrhymes/bulma-clean-theme
title: Parallel Sparse Computation Toolkit
email: eocoe@na.iac.cnr.it
description: Scientific Computing towards the Exascale
permalink: pretty
favicon: /favicon.png # Favicon is in the standard position
livereload: true

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge
  - jemoji

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

google-site-verification: google149f3f1f84e56dc5.html
